### ISSUE TITLE
CHOMP fails when planning for gripper planning group

### ISSUE THREAD

**Issue by captain-yoshi** [moveit/moveit#2542]
### Description

When planning with the planning_group consisting of only my gripper, there is a segfault because of this [line](https://github.com/ros-planning/moveit/blob/master/moveit_planners/chomp/chomp_motion_planner/src/chomp_optimizer.cpp#L222). Also there is a TODO listed in this part code. The `getParentLinkModel` function can return a nullptr as seen in the [documentation](http://docs.ros.org/en/noetic/api/moveit_core/html/classmoveit_1_1core_1_1LinkModel.html#ab3f3635f6017122968e2adae85dd56e3). Below is my backtrace and my planning_group in case something is wrong with it. Planning with OMPL and STOMP works as expected.

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04
* Source or Binary build? Source, master branch

### Backtrace or Console output
[Backtrace](https://gist.github.com/captain-yoshi/016ec318ed36646177736b9fc867ea6c)
Group name for the gripper taken from the srdf file.
```urdf

<group name="robotiq_2f_140">    
    <link name="robotiq_2f_140_base_link" />
    <link name="robotiq_2f_140_left_inner_knuckle" />
    <link name="robotiq_2f_140_left_outer_knuckle" />
    <link name="robotiq_2f_140_left_outer_finger" />
    <link name="robotiq_2f_140_left_inner_finger" />
    <link name="robotiq_2f_140_left_fingertip" />
    <link name="robotiq_2f_140_left_fingerpad" />
    <link name="robotiq_2f_140_right_inner_knuckle" />
    <link name="robotiq_2f_140_right_outer_knuckle" />
    <link name="robotiq_2f_140_right_outer_finger" />
    <link name="robotiq_2f_140_right_inner_finger" />
    <link name="robotiq_2f_140_right_fingertip" />
    <link name="robotiq_2f_140_right_fingerpad" />
    <link name="robotiq_2f_140_tcp" />
 
    <passive_joint name="robotiq_2f_140_left_inner_knuckle_joint" />
    <joint name="robotiq_2f_140_left_outer_knuckle_joint" />
    <passive_joint name="robotiq_2f_140_left_outer_finger_joint" />
    <passive_joint name="robotiq_2f_140_left_inner_finger_joint" />
    <passive_joint name="robotiq_2f_140_left_fingertip_joint" />
    <passive_joint name="robotiq_2f_140_left_fingerpad_joint" />
    <passive_joint name="robotiq_2f_140_right_inner_knuckle_joint" />
    <passive_joint name="robotiq_2f_140_right_outer_knuckle_joint" />
    <passive_joint name="robotiq_2f_140_right_outer_finger_joint" />
    <passive_joint name="robotiq_2f_140_right_inner_finger_joint" />
    <passive_joint name="robotiq_2f_140_right_fingertip_joint" />
    <passive_joint name="robotiq_2f_140_right_fingerpad_joint" />
    <passive_joint name="robotiq_2f_140_tcp_joint" />
</group>    
```

**Comment by Joinjiang** [comment]
it works!  great job

**Comment by DanManN** [comment]
This indeed fixes the problem. Any reason no pull request was made to merge upstream?

**Comment by captain-yoshi** [comment]
@DanManN Trying to reproduce the error. How did you get your error ?
- Planning Interface ? e.g. MoveGroupInterface
- Planning Group ? e.g. hand from moveit_resources panda
- Goal ? e.g. Joint constraint
