### ISSUE TITLE
Error 404 Moveit Noetic documentation

### ISSUE THREAD

**Issue by pucciland95** [moveit/moveit#3602]
### Description

The documentation of MoveIt for ROS Noetic has a broken link. It is possible to navigate it from the Git Hub page but it is not as convenient as the website.

### Steps to reproduce
Navigate to the MoveIt website through: https://ros-planning.github.io/moveit_tutorials/

### Expected behaviour
The website

### Actual behaviour
Error 404

**Comment by Abishalini** [comment]
The project moved from `ros-planning` to `moveit` Github organization so here is the new link - https://moveit.github.io/moveit_tutorials/

Please make a PR to update the link

**Comment by rhaschke** [comment]
Fixed via https://github.com/moveit/moveit_tutorials/pull/823
