### ISSUE TITLE
Moveit Servo with real Franka Panda robot makes the robot shaking/chattering

### ISSUE THREAD

**Issue by torydebra** [moveit/moveit#3633]
### Description

Hi all, I am trying to use moveit servo with the franka panda robot, but, as the title, it is not usable since the robot joints vibrate a lot. 
Robot works fine when using moveit cpp by sending poses, and by setting joint position through `robot_trajectory->setRobotTrajectoryMsg()`. 

I am trying to play with the servo config but no luck:
- increasing `publish_period` (as suggested here https://github.com/moveit/moveit2/issues/645)
- Trying to use both a `position_controllers/JointTrajectoryController (`command_out_type: trajectory_msgs/JointTrajectory`) and position_controllers/JointGroupPositionController  (`command_out_type: std_msgs/FloatMultiarray`)
- `low_pass_filter_coeff`, not sure what it does, but I tried to change also this.

The servo is running on the real time pc connected directly to the panda via cable.
In simulation (gazebo) there seems to be no issues with servo

Anyone has a working configuration for the *real* franka?

For example, this is the output of servo for the second joint, going to the ros controller 
![image](https://github.com/user-attachments/assets/aa0d7c5a-7960-493e-81da-26488f6a909a)

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20.04 Preempt RT kernel
* Binary build, last one available with `apt install ros-noetic-moveit`

**Comment by torydebra** [comment]
Solved by using a joint velocity or effort ros controller. From what I understood it seems that the position ros_controller works in open loop causing such kind of problems

**Comment by piyush-g0enka** [comment]
Hi @torydebra 

I intend to teleoperate a franka using moveit servo in ROS1 similar to you. 
If you don't mind could you share your code with me? It would help me immensely!

Thanks!
