### ISSUE TITLE
Parralel Trajectory Execution not working - asyncMove , asyncExecute

### ISSUE THREAD

**Issue by ron007d** [moveit/moveit#3637]
### Description

I need to execute two trajectory at the same time, where one robot is planning using joint planner and other is planning using Cartesian planning.
#### using `asyncMove`
- it shows `PREEMPTED` and stops the movement of the **panda_1** and completes the **panda_1**

#### Using `asyncExecute`
- execution happens 1 by 1

### Your environment
* ROS Distro:  Noetic
* OS Version:  Ubuntu 20.04
* Binary :  1.1.14
* 
### Steps to reproduce
1. Create a catkin workspace and build this resouces package https://github.com/moveit/moveit_resources
2. run the moveit_resources_dual_arm_panda_moveit_config
```console
roslaunch moveit_resources_dual_panda_moveit_config demo.launch 
```
3. run this python code
```python
from moveit_commander import RobotCommander, MoveGroupCommander
import rospy
from geometry_msgs.msg import Pose

rospy.init_node('moveit_simultaneous_movement_test')
# two robot group
panda_1 = MoveGroupCommander('panda_1')
panda_2 = MoveGroupCommander('panda_2')

# testing asyncMove
panda_1_target_pose = panda_1.get_current_pose()
panda_1_target_pose.pose.position.z += 0.1
panda_1.set_pose_target(pose=panda_1_target_pose)
panda_1_plan = panda_1.plan()

panda_2_target_pose = panda_2.get_current_pose()
panda_2_target_pose.pose.position.z += 0.1
panda_2.set_pose_target(pose=panda_2_target_pose)
panda_2_plan = panda_2.plan()

# when wait is set to false it return asyncMove
panda_1.go(wait=False)
panda_2.go(wait=False)

rospy.sleep(4)

# resetting the position
panda_1.set_named_target('home')
panda_2.set_named_target('home')
panda_1.go()
panda_2.go()

rospy.sleep(3)

# testing asyncExecute
panda_1_target_pose = panda_1.get_current_pose()
panda_1_target_pose.pose.position.z += 0.1
panda_1.set_pose_target(pose=panda_1_target_pose)
panda_1_plan = panda_1.plan()

panda_2_target_pose = panda_2.get_current_pose()
panda_2_target_pose.pose.position.z += 0.1
panda_2.set_pose_target(pose=panda_2_target_pose)
panda_2_plan = panda_2.plan()

panda_1.execute(panda_1_plan[1],wait=False)
panda_2.execute(panda_2_plan[1],wait=False)
```
> One of the suggested work around is using a move group which have two of the groups
> in this case `dual_arm` group

#### dual_arm group does work :white_check_mark:   when I use `set_pose_target` with the panda_1 or panda_2 end effector

but it doesn't work :x: when I need to do Cartesian movement with panda_1 and do another movement with panda_2
```python

way_points = []
target_pose = panda_1.get_current_pose().pose
way_points.append(copy.deepcopy(target_pose))
target_pose.position.z -=0.1
way_points.append(copy.deepcopy(target_pose))
target_pose.position.z +=0.2
way_points.append(copy.deepcopy(target_pose))
target_pose.position.z -=0.1
way_points.append(copy.deepcopy(target_pose))
panda_1_trajectory, fraction = panda_1.compute_cartesian_path(waypoints= way_points,
                                                      eef_step=0.01,
                                                      jump_threshold=0.0)

way_points = []
target_pose = panda_2.get_current_pose().pose
way_points.append(copy.deepcopy(target_pose))
target_pose.position.z -=0.1
way_points.append(copy.deepcopy(target_pose))
target_pose.position.z +=0.2
way_points.append(copy.deepcopy(target_pose))
target_pose.position.z -=0.1
way_points.append(copy.deepcopy(target_pose))
panda_2_trajectory, fraction = panda_2.compute_cartesian_path(waypoints= way_points,
                                                      eef_step=0.01,
                                                      jump_threshold=0.0)


dual_arm.execute(trajectory=panda_1_trajectory,wait=False)
dual_arm.execute(trajectory=panda_2_trajectory,wait=False)
```
### Expected behaviour
Both trajectory starts execution

### Actual behaviour
first trajectory get executed then other

### Backtrace or Console output
```console
Stopping execution due to preempt request
```
#### when trying to add end effector link to dual arm
```python
dual_arm.set_end_effector_link(link_name=panda_1.get_end_effector_link())
```
output : 
```console
File /opt/ros/noetic/lib/python3/dist-packages/moveit_commander/move_group.py:101, in MoveGroupCommander.set_end_effector_link(self, link_name)
     [99](https://file+.vscode-resource.vscode-cdn.net/opt/ros/noetic/lib/python3/dist-packages/moveit_commander/move_group.py:99) """Set the name of the link to be considered as an end effector"""
    [100](https://file+.vscode-resource.vscode-cdn.net/opt/ros/noetic/lib/python3/dist-packages/moveit_commander/move_group.py:100) if not self._g.set_end_effector_link(link_name):
--> [101](https://file+.vscode-resource.vscode-cdn.net/opt/ros/noetic/lib/python3/dist-packages/moveit_commander/move_group.py:101)     raise MoveItCommanderException("Unable to set end effector link")

MoveItCommanderException: Unable to set end effector link
```

**Comment by rhaschke** [comment]
You report multiple issues here:
1. Parallel trajectory execution is not working
  This is by design. If you plan for multiple groups independently and execute the resulting trajectories, they might actually collide, because planning didn't consider the motion of the other arm. Interestingly, move_group reacts differently to a corresponding attempt:
   - If you use `go()` when another trajectory is executing, move_group complains:
`ERROR ros.moveit_ros_planning.trajectory_execution_manager: Cannot push a new trajectory while another is being executed`
   - If you use `execute()` when another trajectory is executing, move_group preempts the previous trajectory.

   There is a pending PR #3243 for this.
2. `dual_arm.set_end_effector_link()` not working
   As the `dual_arm` group is actually a robot _tree_ with multiple end effectors, the call to `set_end_effector_link()` is ambiguous and therefore rejected.
