### ISSUE TITLE
Moveit Servo ignores allowed collision matrix for external objects

### ISSUE THREAD

**Issue by torydebra** [moveit/moveit#3639]
### Description

I noticed that `moveit_servo` ignores the allowed collision matrix for world collisions, hence considering always them. The issue is here:
https://github.com/moveit/moveit/blob/361de4b9295cd867b4ff446f26c8349d8a53cb94/moveit_ros/moveit_servo/src/collision_check.cpp#L117-L118

Indeed, the `acm_` is not passed to this method, while instead it is passed when checking for self-collisions:
https://github.com/moveit/moveit/blob/361de4b9295cd867b4ff446f26c8349d8a53cb94/moveit_ros/moveit_servo/src/collision_check.cpp#L125-L126

I simply solved passing the `acm_` also to `checkRobotCollision()`, there was any reason for not doing so?
```c++
  getLockedPlanningSceneRO()->getCollisionEnv()->checkRobotCollision(collision_request_, collision_result_,
                                                                     *current_state_, acm_);
```

### Your environment
* ROS Distro: Noetic
* OS Version: Ubuntu 20
* Binary build

**Comment by rhaschke** [comment]
Thanks for reporting this issue. I don't see a reason for not passing the ACM. Maybe, @AndyZe knows more about that.
Please file a PR applying your fix.

**Comment by torydebra** [comment]
PR Opened!
