### ISSUE TITLE
Writting a RUST wrapper for MoveIt

### ISSUE THREAD

**Issue by Akumar201** [moveit/moveit#3646]
**Is your feature request related to a problem? Please describe.**

As Rust continues to grow in popularity, especially in systems programming and robotics, it would be great to have a Rust wrapper for MoveIt. Currently, integrating MoveIt into Rust-based projects is difficult, and a wrapper would simplify this process and allow seamless integration with Rust projects.

**Describe the solution you'd like**

I propose writing a Rust wrapper for MoveIt that exposes its core functionalities in a way that is idiomatic to Rust. This would allow Rust developers to easily integrate MoveIt into their projects while leveraging Rust's safety and concurrency features.

**Describe alternatives you've considered**

-  Manually integrating MoveIt with Rust using FFI (Foreign Function Interface), but this can be cumbersome and error-prone.
-  Relying on C++ as the primary language, but this makes it difficult for Rust projects to use MoveIt natively.

**Additional context**

This wrapper could serve as a bridge between MoveIt and the growing Rust ecosystem, allowing for safer and more efficient integration of robotics functionalities into Rust-based projects.

I am looking for collaboration with the people who are interested in this.

**Comment by rhaschke** [comment]
This is nothing to be considered for MoveIt1. Maybe the [MoveIt2](https://github.com/moveit/moveit2) team is interested in that.
