### ISSUE TITLE
Controller 'scaled_pos_joint_traj_controller' failed with error PATH_TOLERANCE_VIOLATED:

### ISSUE THREAD

**Issue by 1264433432** [moveit/moveit#3649]
I want to control the robotic arm UR5 through Moveit and visualize it in Gazebo.
I implemented my idea through three pieces of code.
①roslaunch ur_gazebo ur5_bringup.launch
②roslaunch ur5_moveit_config moveit_planning_execution.launch sim:=true
③roslaunch ur5_moveit_config moveit_rviz.launch config:=true
In rviz, planning can be approved, but when I execute, it shows' failed '
Error display ：Controller 'scaled_pos_joint_traj_controller' failed with error PATH_TOLERANCE_VIOLATED: shoulder_pan_joint path error -2.492077
In the relevant posts, it was found that there may be a problem with the parameter settings of the controller, which is related to the tolerance error.I'm going to search for the files of the controller，There are two YAML files, one located in the moveit_comfig/config path and the other in the gazebo/config path. The moveit_comfig/config file contains the scaled_pos_joint_traj_comtrol in the error message. I would like to know what the relationship between these two files is and how to adjust it to make the error disappear.

ros_controllers :moveit_comfig/config
controller_list:
- name: "scaled_pos_joint_traj_controller"
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

ur5_controllers: gazebo/config 
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: &loop_hz 125

eff_joint_traj_controller:
  type: effort_controllers/JointTrajectoryController
  joints: &robot_joints
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
  gains: # Required because we're controlling an effort interface
    shoulder_pan_joint: {p: 4000,  d: 200, i: 1, i_clamp: 1}
    shoulder_lift_joint: {p: 10000,  d: 200, i: 1, i_clamp: 1}
    elbow_joint: {p: 2000,  d: 20, i: 1, i_clamp: 1}
    wrist_1_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    wrist_2_joint: {p: 500,  d: 1, i: 1, i_clamp: 1}
    wrist_3_joint: {p: 10,  d: 0.1, i: 0, i_clamp: 1} 
  constraints
    goal_time: 0.6
    stopped_velocity_tolerance: 0.0
    shoulder_pan_joint: {trajectory: 0.1, goal: 0.0}
    shoulder_lift_joint: {trajectory: 0.1, goal: 0.0}
    elbow_joint: {trajectory: 0.1, goal: 0.0}
    wrist_1_joint: {trajectory: 0.1, goal: 0.0}
    wrist_2_joint: {trajectory: 0.1, goal: 0.0}
    wrist_3_joint: {trajectory: 0.1, goal: 0.0}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_eff_controller:
  type: effort_controllers/JointGroupEffortController
  joints: *robot_joints

pos_joint_traj_controller:
  type: position_controllers/JointTrajectoryController
  joints: *robot_joints
  constraints:
    goal_time: 0.6
    stopped_velocity_tolerance: 0.0
    shoulder_pan_joint: {trajectory: 0.1, goal: 0.0}
    shoulder_lift_joint: {trajectory: 0.1, goal: 0.0}
    elbow_joint: {trajectory: 0.1, goal: 0.0}
    wrist_1_joint: {trajectory: 0.1, goal: 0.0}
    wrist_2_joint: {trajectory: 0.1, goal: 0.0}
    wrist_3_joint: {trajectory: 0.1, goal: 0.0}
  stop_trajectory_duration: 0.5
  state_publish_rate: *loop_hz
  action_monitor_rate: 10

joint_group_pos_controller:
  type: position_controllers/JointGroupPositionController
  joints: *robot_joints

**Comment by rhaschke** [comment]
Regarding the relation of these two files: The Gazebo config file configures the ROS controller manager (running inside Gazebo). The MoveIt file configures, which controllers are used by MoveIt to execute motions.
This is nicely explained in the [tutorial](https://moveit.github.io/moveit_tutorials/doc/controller_configuration/controller_configuration_tutorial.html).

What I am confused about is the name `scaled_pos_joint_traj_controller` referenced in the MoveIt config file.
This name is not configured as a controller in Gazebo. However, the controller seems to be executed.

The `PATH_TOLERANCE_VIOLATED` error is triggered if the controller cannot track the planned trajectory.
This is well documented on [ROS answers](https://answers.ros.org/question/325103/how-to-solve-problem-with-path_tolerance_violated-in-moveit/).

Conclusion: Please read the docs and other online resources before posing a question here!
